//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ex_Interview_Round1
    {
        public int ID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string Status { get; set; }
        public string LoginType { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_Candidate tbl_Candidate { get; set; }
        public virtual tbl_PostedJobs tbl_PostedJobs { get; set; }
    }
}
