//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Task()
        {
            this.tbl_Ex_Task_Round3 = new HashSet<tbl_Ex_Task_Round3>();
        }
    
        public long ID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> JTypeID { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> InsertedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ex_Task_Round3> tbl_Ex_Task_Round3 { get; set; }
        public virtual tbl_jobtype tbl_jobtype { get; set; }
        public virtual tbl_positions tbl_positions { get; set; }
    }
}
