//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Candidate()
        {
            this.tbl_Ex_Interview_Round1 = new HashSet<tbl_Ex_Interview_Round1>();
            this.tbl_Ex_Quiz_Round2 = new HashSet<tbl_Ex_Quiz_Round2>();
            this.tbl_Ex_Task_Round3 = new HashSet<tbl_Ex_Task_Round3>();
            this.tbl_results_round2 = new HashSet<tbl_results_round2>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string CNIC { get; set; }
        public string Email { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> RoundNo { get; set; }
        public byte[] Attachment { get; set; }
        public string Extension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ex_Interview_Round1> tbl_Ex_Interview_Round1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ex_Quiz_Round2> tbl_Ex_Quiz_Round2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ex_Task_Round3> tbl_Ex_Task_Round3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_results_round2> tbl_results_round2 { get; set; }
        public virtual tbl_City tbl_City { get; set; }
    }
}
