//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ex_Quiz_Round2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ex_Quiz_Round2()
        {
            this.tbl_results_round2 = new HashSet<tbl_results_round2>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> JobID { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_Candidate tbl_Candidate { get; set; }
        public virtual tbl_PostedJobs tbl_PostedJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_results_round2> tbl_results_round2 { get; set; }
    }
}
