//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_questionBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_questionBank()
        {
            this.tbl_results_round2 = new HashSet<tbl_results_round2>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> JobTypeId { get; set; }
        public string Question { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string CorrectAnswer { get; set; }
    
        public virtual tbl_jobtype tbl_jobtype { get; set; }
        public virtual tbl_positions tbl_positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_results_round2> tbl_results_round2 { get; set; }
    }
}
